### ISSUE TITLE
Show highlights when printing a page

### ISSUE THREAD

**Issue by kennysong** [hypothesis/browser-extension#1039]
I've had a few cases recently where I wanted to share my (private) highlighted article, and the easiest way to do that was to print/export the page as a PDF. 

However, highlights disappear when the page is printed. Would be great if there's a way to toggle this! 

Or, if you can point me to the code (CSS media query?) that is disabling highlights, I can play around with it myself.

**Comment by robertknight** [comment]
Thanks for the feedback. I agree it would be useful to have this option.

On a technical level, the issue is that the Print button in the PDF viewer doesn't actually print the content you see on screen. Instead the normal UI (`#outerContainer`) gets temporarily hidden and a print-friendly version of the page is rendered in a different area (the `#printContainer` element). After the content has been sent for printing, the print-friendly version is hidden and the normal UI is shown. The issue with Hypothesis is that highlights are not rendered on top of the print-friendly version of the content, only the on-screen version.

**Comment by kennysong** [comment]
Hmm got it, that seems more difficult to fix than a CSS tweak. 

Do you know of any workarounds for now? Copy & pasting content doesn't seem to carry over highlights either.

**Comment by robertknight** [comment]
> Do you know of any workarounds for now?

Technically adept users might be able to meet their needs using [our API](https://h.readthedocs.io/en/latest/api/). Unfortunately I don't know of an easy solution for printing PDFs with highlights within the Hypothesis extension.

For HTML content on the other hand, highlights do appear if you turn on the "Background graphics" option under "More settings..." in Chrome's print dialog, or equivalent options in other browsers.

**Comment by kennysong** [comment]
> For HTML content on the other hand, highlights do appear if you turn on the "Background graphics" option under "More settings..." in Chrome's print dialog, or equivalent options in other browsers.

Ah that's perfect! I wanted to print an HTML article as a PDF. This works perfectly for me. 

Noted that this doesn't work for PDFs highlights.

(I'm happy to close this issue now.)
