### ISSUE TITLE
Extension fails to log in

### ISSUE THREAD

**Issue by mkdir-washington-edu** [hypothesis/browser-extension#263]
Steps to reproduce:

1. Open the sidebar using the extension and log out.
2. Click the Log in button
3. The authorization window opens and immediately closes.
4. Delete cookies from hypothes.is
5. Press log in again
6. The authorization window stays open.
7. Log in via the window.
8. The sidebar still doesn't log in.

**Comment by klemay** [comment]
Note: Both Lyza and I tried to reproduce in the embedded client and were not able to; this seems to be an issue in the extension

**Comment by robertknight** [comment]
The issue was a caching configuration change in Cloudflare which caused `/api/profile` responses to be inappropriately cached. As a result, the cached `/api/profile` response for the _logged out_ state was returned after logging in.

The cache setting change in Cloudflare has been undone but some browsers may have an incorrect response cached which will expire in ~15 minutes.

Until that expiry happens, the issue can be worked around as follows:

Go to the Chrome menu (macOS) or "File" on Windows => Clear Browsing Data => Check only “Cached images and files” in the “Basic” tab => click Clear Data.

**Comment by robertknight** [comment]
Additional details (for H staff) in this thread: https://hypothes-is.slack.com/archives/C03QZM0K4/p1576000129050500?thread_ts=1575998723.037600&cid=C03QZM0K4
