### ISSUE TITLE
Extension fails to inject after enabling it, then activating on previously open tab

### ISSUE THREAD

**Issue by robertknight** [hypothesis/browser-extension#37]
**Steps to reproduce:**

1. Install the extension but disable it from chrome://extensions by unchecking the "Enable" box next to the extension's details
2. Open a tab at some HTTP URL
3. Re-enable the extension
4. Switch back to the tab and click the extension's toolbar button

**Expected result:**

The extension activates and injects the client into the page

**Actual result:**

The extension's toolbar button activates but the client is not injected into the page. After reloading the page, the client is successfully injected.

The problem only affects tabs that were opened prior to re-enabling the extension.

**Comment by seanh** [comment]
I was able to reproduce this effect (toolbar button activates, but no sidebar) today, but I was uninstalling and reinstalling the extension rather than enabling and disabling. It was only happening on tabs that were already open when I re-installed the extension, not happening on other tabs, and when I reloaded the broken tab the problem went away.

Also:

1. Quit Chrome
2. Re-launch Chrome, it opens all the tabs you had open last time
3. Try to launch h in one of those tabs => no sidebar. I seem to be able to reliably reproduce this on http://boingboing.net/ and some other sites, but reliably _don't_ reproduce it on https://lobste.rs/

Looks like Dan was also having a similar problem: https://hypothes-is.slack.com/archives/C4K6M7P5E/p1497547469362566

No leads yet on what is actually happening
