### ISSUE TITLE
annotator.bundle.js?cc2808:20 Uncaught (in promise) TypeError: URL is not a constructor

### ISSUE THREAD

**Issue by jeka57** [hypothesis/browser-extension#440]
Hi! I have Google Chrome (last official version) and Hypothesis 1.584.0.5 (Official Build).
When I trying to run the extension on https://support.kaspersky.com/ get nothing on the screen and following errors in the console:
```
annotator.bundle.js?cc2808:20 Uncaught (in promise) TypeError: URL is not a constructor
    at a._getDocumentHref (annotator.bundle.js?cc2808:20)
    at a._getLinks (annotator.bundle.js?cc2808:20)
    at a.getDocumentMetadata (annotator.bundle.js?cc2808:20)
    at new a (annotator.bundle.js?cc2808:20)
    at m.addPlugin (annotator.bundle.js?cc2808:20)
    at new b (annotator.bundle.js?cc2808:20)
    at new m (annotator.bundle.js?cc2808:20)
    at annotator.bundle.js?cc2808:20
```
Any thoughts why it would happens?

**Comment by robertknight** [comment]
It looks like that page defines a global variable named `URL` which conflicts with the browser API of the same name. On a normal web page, this works:

```js
new URL('https://example.com')
```

On that particular page, it triggers an error because of this global variable.

In future we might be able to make the Chrome extension immune to this kind of problem. 

As a workaround for technical users, you can paste this into the browser console to temporarily fix the issue:

```js
URL = document.body.appendChild(document.createElement('iframe')).contentWindow.URL
```

Note that this might break some functionality on the page.

**Comment by jeka57** [comment]
Wow, it works for me! Thanks, Robert!
