### ISSUE TITLE
Why does Chrome browser extension ask for geolocation, camera & microphone settings access?

### ISSUE THREAD

**Issue by billfitzgerald** [hypothesis/browser-extension#46]
While adding the Chrome plugin this morning from the Chrome store, I received the message below that states that the extension needs to be able to change website's access to geolocation settings, camera, and microphone.

![why](https://user-images.githubusercontent.com/1602849/28249064-0e70e814-6a04-11e7-9615-902c5694169c.png)

I'm assuming that this message appears because of how these permissions are bundled, but from a functional place,  

I'm assuming that this is a non-issue related more to how the Chrome store auto-generates messages based on what permissions are requested, but given that the message pops up on install, I'd love to know more about:

- why does the annotation plugin need to be able to access geolocation, camera, or microphone settings?
- if the plugin does need to be able to adjust access to these settings, how are users notified that their defaults are getting changed?
- does any data collected via mic/camera/geolocation get sent back to hypothes.is servers (in addition to the originating web site)?

Thanks for any info you can provide here.

Also, some general technical details: I'm running Ubuntu Linux 16.04, latest Chrome - glad to share additional technical details privately if they are helpful/relevant.

**Comment by robertknight** [comment]
> I'm assuming that this is a non-issue related more to how the Chrome store auto-generates messages based on what permissions are requested

Hello @billfitzgerald - you are completely correct. This is related [to a change](https://github.com/hypothesis/browser-extension/blob/7e0823d42db2140d6d99b7d0e8009189031155ff/src/common/install.js#L59) that the extension makes to your cookie whitelist (adding "https://hypothes.is" to an always-allow whitelist, even if third party cookies are otherwise blocked) in order to enable logging in to the service from the sidebar to work.

You can see the change at the bottom of this screenshot:

<img width="711" alt="screenshot 2017-07-17 09 21 29" src="https://user-images.githubusercontent.com/2458/28260109-739a4b7c-6ad1-11e7-9559-e9acc09e4f73.png">

The extension **does not read or modify your camera, geolocation or microphone settings or use these devices in any way**. Unfortunately these permissions are part of the same set of permissions that allows the software to change the cookie whitelist.

We are currently in the process of changing the way authentication works in the client and should be able to remove the need to ask for this permission after that is done.

**Comment by robertknight** [comment]
I'm going to leave this open so we can close this once the client & service's OAuth implementation is complete.

**Comment by billfitzgerald** [comment]
@robertknight - thank you! That's great to know, both re current status and future plans.

**Comment by robertknight** [comment]
The fix is currently in QA testing. Everything looks good so I'll release it on Monday next week.
