### ISSUE TITLE
Limited compatibility w/ Dark Reader extension

### ISSUE THREAD

**Issue by Acumane** [hypothesis/browser-extension#830]
Dark mode plugins like [Dark Reader](https://chrome.google.com/webstore/detail/dark-reader/eimadpbcbfnmbkopoojfekhnkhdbieeh) affect some elements, but not the body of the side menu. Is this a limitation of the [API](https://hypothes.is/api/)?

![ex](https://user-images.githubusercontent.com/94324138/160258562-adfff864-d63c-4ff2-840a-5e14ba711b86.gif)

**Comment by robertknight** [comment]
The sidebar is inside an iframe that isolates it from the rest of the page. This sidebar is part of our extension and I don't think Dark Reader would be allowed to inject code into it, due to security restrictions imposed on Chrome extensions.

I'm closing this issue because I don't think it can be resolved. What we could consider though is general support for the dark mode in the client, when your system/browser is configured to use the dark-mode version of websites where available.
